name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:


jobs:

  # ┌─────────────────────────────────────┐
  # │                                     │
  # │          CREATE A RELEASE           │
  # │                                     │
  # └─────────────────────────────────────┘
  release:

    name: Build Release
    runs-on: ubuntu-latest
    steps:

      # Download the latest release from the
      # private repository.
      #
      - uses: robinraju/release-downloader@v1.6
        with: 
          repository: "ioroot/HouseQuests-Private"
          latest: true
          fileName: "HouseQuests.*"
          out-file-path: "artifacts"
          token: ${{ secrets.PAT }}

      # Create a new release
      # Use the RELEASE.md text for the body text.
      #
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: RELEASE.md
          draft: false
          prerelease: false


      - name: Upload artifact and release
        uses: nanoufo/action-upload-artifacts-and-release-assets@main
        with:
          path: |
            artifacts/*
          upload-release-files: true
          if-no-files-found: error
          release-upload-url: ${{ steps.create_release.outputs.upload_url }} 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}